  #配置端口
server:
  port: 8082

  #扫描Mybatis mapper文件
mybatis:
  mapperLocations: classpath:mappers/*.xml

  #配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ec_manage?useUnicode=true&characterEncoding=utf8&serverTimezone=CTT
    username: root
    password: qw332613
    driver-class-name: com.mysql.cj.jdbc.Driver

  #配置SQL打印
logging:
  level:
    org.lrh.dao: debug
